package com.yandex.tracker.model;

public enum Endpoint {
    GET_PRIORITIZED_TASKS,
    GET_HISTORY,
    GET_TASKS,
    GET_TASK_BY_ID,
    POST_CREATE_TASK,
    POST_UPDATE_TASK,
    DELETE_TASK_BY_ID,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_CREATE_SUBTASK,
    POST_UPDATE_SUBTASK,
    DELETE_SUBTASK_BY_ID,
    GET_EPICS,
    GET_EPIC_BY_ID,
    GET_EPIC_SUBTASKS,
    POST_CREATE_EPIC,
    DELETE_EPIC_BY_ID,
    UNKNOWN
}
